[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/pdf/*"
  to = "/.netlify/functions/generar-pdf"
  status = 200

